version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    php:
        build: ./phpserver
        expose:
            - "9000"
        volumes:
            - ./data/wwwSite:/var/www
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - db
    nginx:
        build: ./webserver
        ports:
            - "80:80"
        links:
            - php:php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
